on:
  push:
    branches:
      - master

name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: snack-og-image
      uses: ./.github/actions/snack-og-image
    - name: CNAME settings
      run: |
        if [[ "${{ secrets.CNAME }}" != "" ]]; then
          echo "${{ secrets.CNAME }}" > static/CNAME
        fi
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        HUGO_VERSION: "0.69.0"
