on:
  push:
    branches:
      - main

name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: snack-og-image
      uses: ./.github/actions/snack-og-image
    - name: CNAME settings
      run: |
        if [[ "${{ secrets.CNAME }}" != "" ]]; then
          echo "${{ secrets.CNAME }}" > static/CNAME
          base_url="https://${{ secrets.CNAME }}/"
        else
          github_user="${GITHUB_REPOSITORY%/*}"
          github_repo="${GITHUB_REPOSITORY#*/}"
          if [[ "$github_repo" = "$github_user.github.io" ||
                "$github_repo" = "$github_user.github.com" ]]; then
            base_url="https://$github_user.github.io/"
          else
            base_url="https://$github_user.github.io/$github_repo/"
          fi
        fi
        sed \
          --regexp-extended \
          --in-place \
          's|(baseURL\s*=\s*")http?s://[^"]+(")|\1'"$base_url"'\2|' \
          config.toml
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        HUGO_VERSION: "0.69.0"
